"""empty message

Revision ID: 5b13799c2fc8
Revises: 
Create Date: 2024-11-05 11:06:28.053863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b13799c2fc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('clinic_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.CheckConstraint('phone_number > 0', name='phone_number_positive'),
    sa.PrimaryKeyConstraint('clinic_number'),
    sa.UniqueConstraint('name')
    )
    op.create_table('doctor',
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.CheckConstraint("email LIKE '%_@__%.__%'"),
    sa.CheckConstraint("gender IN ('Male', 'Female', 'Other')"),
    sa.CheckConstraint('age > 0'),
    sa.CheckConstraint('date_birth > 0 AND date_birth < CURRENT_DATE'),
    sa.CheckConstraint('dni > 0'),
    sa.CheckConstraint('phone_number > 0'),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('image_patient', sa.String(length=255), nullable=True),
    sa.CheckConstraint("email LIKE '%_@__%.__%'"),
    sa.CheckConstraint("gender IN ('Male', 'Female', 'Other')"),
    sa.CheckConstraint('date_birth > 0 AND date_birth < CURRENT_DATE'),
    sa.CheckConstraint('phone_number > 0'),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_table('diagnostic',
    sa.Column('cod', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('res', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_result', sa.Date(), nullable=True),
    sa.Column('image_diagnostic', sa.String(length=255), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dni'], ['patient.dni'], ),
    sa.PrimaryKeyConstraint('cod')
    )
    op.create_table('works_at',
    sa.Column('clinic_number', sa.Integer(), nullable=False),
    sa.Column('doctor_dni', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_number'], ['clinic.clinic_number'], ),
    sa.ForeignKeyConstraint(['doctor_dni'], ['doctor.dni'], ),
    sa.PrimaryKeyConstraint('clinic_number', 'doctor_dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_at')
    op.drop_table('diagnostic')
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('clinic')
    # ### end Alembic commands ###
